# このファイルは、「docker-compose up」の実行時にロードされます。設定は開発環境用です。
# ./volumes/

version: '3'

services:
  db:
    volumes:
      # My SQL環境を上書きします。
      - ./mysql/server.cnf:/etc/mysql/conf.d/server.cnf

      # mysqlファイルをホストファイルシステムに保存することもできます。
      # - ./volumes/mysql:/var/lib/mysql

      # コンテナの生成時に/docker-entrypoint-initdb.d/*.sql.gzが存在する場合、
      # mariadbによって読み込まれ、1回だけ復元されます。
      # - ./initdb.sql.gz:/docker-entrypoint-initdb.d/initdb.sql.gz
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"

  php:
    volumes:
      # put your drupal source code and mount as volume.
      - ./volumes/drupal:/var/www/html:cached
      # Replace volume to this to use docker-sync for mac OS users to resolve performance issue.
      # See also: https://github.com/docker/for-mac/issues/77
      # - drupal_source:/var/www/html:rw
      # allocate large memory_limit for drush.
      - ./php/php/php.ini:/usr/local/etc/php/php.ini
      # override php-fpm config to use xdebug with port 9000.
      - ./php/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      # override sendmail_path to use mailhog
      - ./php/php-fpm/sendmail_path.conf:/usr/local/etc/php-fpm.d/sendmail_path.conf
      # use your host's ssh key, drushrc
      # - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      # - ~/.drush/aliases.drushrc.php:/root/.drush/aliases.drushrc.php:ro

  web:
    environment:
      VIRTUAL_HOST: localhost
    volumes:
      # Drupal コードのマウント
      - ./volumes/drupal:/var/www/html:cached
      # Replace volume to this to use docker-sync for mac OS users to resolve performance issue.
      # See also: https://github.com/docker/for-mac/issues/77
      # - drupal_source:/var/www/html:rw
      # override nginx config to execute drupal through the php container.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/default_for_drupal_composer.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/override_for_development.conf:/etc/nginx/conf.d/override_for_development.conf

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/override_for_development.conf:/etc/nginx/conf.d/override_for_development.conf
    ports:
      # ポート5580番を80番に接続
      - "5580:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306
    links:
      - db
    volumes:
      - ./phpmyadmin/php-fpm.conf:/etc/php-fpm.conf
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
       - 8080:80

  dozzle:
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
       - 8081:8080

#volumes:
#  drupal_source:
#    external: true
